// Client-side blog feed renderer.
// Reads /public/data/posts.json (generated by scripts/build.js from content/posts/*.md)
// and renders into any element matching [data-blog-feed].
//
// data-blog-feed attribute values:
//   "homepage" - top 3 published posts, card grid for index.html
//   "all"      - full list for blog.html
//
// Each post card uses data-i18n-static="true" so the i18n loop ignores it.

const VI_MONTHS = [
  "tháng 1", "tháng 2", "tháng 3", "tháng 4", "tháng 5", "tháng 6",
  "tháng 7", "tháng 8", "tháng 9", "tháng 10", "tháng 11", "tháng 12",
];

function formatDate(iso, lang) {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  if (lang === "en") {
    return d.toLocaleDateString("en-GB", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  }
  return `${d.getDate()} ${VI_MONTHS[d.getMonth()]}, ${d.getFullYear()}`;
}

function escapeHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderCard(post, lang) {
  const date = formatDate(post.date, lang);
  const readMore = lang === "en" ? "Read more →" : "Đọc thêm →";
  return `
    <article class="card blog-card">
      <div class="blog-card__meta">${escapeHtml(date)}</div>
      <h3 class="blog-card__title">${escapeHtml(post.title)}</h3>
      <p class="blog-card__excerpt">${escapeHtml(post.excerpt || "")}</p>
      <a class="blog-card__link" href="/pages/blog/${escapeHtml(post.slug)}.html">${readMore}</a>
    </article>
  `;
}

function renderEmpty(lang) {
  const msg =
    lang === "en"
      ? "No posts yet. Check back soon!"
      : "Chưa có bài viết nào. Hãy theo dõi sớm nhé!";
  return `
    <div class="blog-empty">
      <img class="blog-empty__img" src="/images/blog-empty-state.jpg" alt="" loading="lazy" />
      <p class="blog-empty__msg">${msg}</p>
    </div>
  `;
}

async function loadPosts() {
  try {
    const res = await fetch("/data/posts.json", { cache: "no-cache" });
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data) ? data : [];
  } catch (_e) {
    return [];
  }
}

function currentLang() {
  try {
    return localStorage.getItem("lang") || "vi";
  } catch {
    return "vi";
  }
}

async function renderFeeds() {
  const targets = document.querySelectorAll("[data-blog-feed]");
  if (!targets.length) return;
  const posts = (await loadPosts()).filter((p) => p.published);
  posts.sort((a, b) => new Date(b.date) - new Date(a.date));
  const lang = currentLang();

  targets.forEach((el) => {
    const mode = el.getAttribute("data-blog-feed");
    const list = mode === "homepage" ? posts.slice(0, 3) : posts;
    if (!list.length) {
      el.innerHTML = renderEmpty(lang);
      return;
    }
    el.innerHTML = list.map((p) => renderCard(p, lang)).join("");
  });
}

document.addEventListener("DOMContentLoaded", renderFeeds);
window.addEventListener("lang-change", renderFeeds);
